# roles/paperless_lxc/tasks/main.yml

- name: ensure cifs-utils is installed
  ansible.builtin.apt:
    name: cifs-utils
    state: present
    update_cache: yes

- name: ensure paperless system group exists with fixed gid
  ansible.builtin.group:
    name: paperless
    gid: "{{ pgid }}"
    system: yes
    state: present
  tags: paperless

- name: ensure paperless system user exists with fixed uid/gid
  ansible.builtin.user:
    name: paperless
    uid: "{{ puid }}"
    group: paperless
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
    state: present
  tags: paperless

- name: create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /srv/apps/paperless/data
    - /srv/apps/paperless/pgdata
    - /srv/apps/paperless/redisdata
    - /srv/apps/alloy
    - /srv/apps/promtail
  tags: docker

- name: ensure correct directory ownership
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 999
    group: 999
    mode: '0700'
  notify: restart all containers
  tags: paperless
  loop:
    - /srv/apps/paperless/data
    - /srv/apps/paperless/pgdata
    - /srv/apps/paperless/redisdata

# not needed - only the other clients need the SMB share. the LXC can use only the NFS share
- name: create smb share
  import_tasks: mount-smb.yml
  when: false # never run
  tags: smb

- name: create environment file from template
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_compose_dir }}/.env"
    mode: '0600'
  notify: restart paperless
  tags: docker

- name: upload config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  loop:
    - alloy:
      src: templates/config.alloy
      dest: /srv/apps/alloy/config.alloy
  become: true
  tags: alloy
  notify: restart alloy

- name: copy docker-compose.yml
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
  tags: docker
  notify: restart all containers

- name: Configure sleep hours
  import_role:
    name: sleep_hours
  tags: sleep
