---
# Zsh installation

- name: Install Zsh from apt
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Change default shell to Zsh for specified users
  ansible.builtin.user:
    name: "{{ item.split(':')[0] }}"
    shell: /usr/bin/zsh
  loop: "{{ target_shell_users }}"
  become: true
  when: shell_environment_set_default_shell | bool
