---

- name: restart docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: always
    dependencies: true
  become: false

- name: restart alloy 
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - alloy
    state: present
    recreate: always
    dependencies: true
  become: false
