# media_vm/files/docker-compose.yml



# media_stack_config_dir is `/srv/media/config`
# media_stack_mount_dir is `/mnt/media`

# CONFIG_DIR={{ media_stack_config_dir }}
# DOWNLOAD_DIR={{ media_stack_mount_dir }}/library/downloads
# MEDIA_DIR={{ media_stack_mount_dir }}/library
---

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CALIBRE_PASSWORD}
      - CLI_ARGS=
    volumes:
      - ${CONFIG_DIR}/calibre:/config
      - /mnt/media/media:/media
      - /mnt/media/library:/library
    ports:
      - "8180:8080"  # GUI
      - "8181:8081"  # Content server
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ${CONFIG_DIR}/calibre-web:/config
      - /mnt/media/media:/media
      - /mnt/media/library:/library
    ports:
      - "8083:8083"
    restart: unless-stopped

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/kavita:/config
      - /mnt/media/media:/media
      - /mnt/media/library:/library
    ports:
      - 5000:5000
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/library

    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/library
    ports:
      - "7878:7878"
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080 # qBittorrent WebUI
      - 8081:8081 # sabnzbd WebUI, set in config file.
      - 6881:6881 # BitTorrent port
      - 6881:6881/udp
      - 3189:3189 # endpoint port
      - 8000:8000/tcp # control server port
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    healthcheck:
      test: ["CMD", "wget", "-qO-", "https://ifconfig.me"]
      interval: 60s
      timeout: 10s
      retries: 3
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - FIREWALL=on
      - WIREGUARD_ENDPOINT=${WIREGUARD_ENDPOINT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - OWNED_ONLY=yes
      - TZ=Europe/Amsterdam
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_USERNAME=${QBITTORRENT_USERNAME}
      - WEBUI_PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
      # /srv/media/config 
      - ${CONFIG_DIR}:/config
      # /mnt/media/library/downloads 
      - ${DOWNLOAD_DIR}:/downloads
      # /mnt/media/library
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=info
    volumes:
      - ${CONFIG_DIR}/jellyseer:/app/config
    restart: unless-stopped


  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    ports:
      - "6767:6767"
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}:/library
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true  # required for some metrics

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

