# docker-compose.yml (abstracted variables + host-mounted SMB shares)

---

services:

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_USERNAME=${QBITTORRENT_USERNAME}
      - WEBUI_PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
      # /srv/media/config 
      - ${CONFIG_DIR}:/config
      # /mnt/media/library/downloads 
      - ${DOWNLOAD_DIR}:/downloads
      # /mnt/media/library
      - ${MEDIA_DIR}:/media

    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    ports:
      - "7878:7878"
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    ports:
      - "6767:6767"
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
