# proxmox_node/files/docker-compose.yml

---

services:
  tunarr:
    image: chrisbenincasa/tunarr:latest-vaapi
    container_name: tunarr
    restart: unless-stopped
    ports:
      - "8000:8000"     # Web UI and API
      - "8001:8001"     # HLS/Stream endpoint
    environment:
      - LOG_LEVEL=INFO
      - TZ=Europe/Amsterdam
      - TRANSCODER_MODE=vaapi
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/apps/tunarr:/config/tunarr
      - /mnt/media/library:/library  # kids shows, family movies 
      - /mnt/media/media:/media # youtube videos, photography videos

  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    restart: unless-stopped
    mem_limit: 8g
    mem_reservation: 4g
    ports:
      - "8096:8096"
    environment:
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/apps/jellyfin/appdata:/config
      - /srv/apps/jellyfin/cache:/cache
      - /mnt/media/library:/library # kids shows, family movies, etc
      - /mnt/media/media:/media # youtube videos, photography videos
    privileged: true

  # node exporter is running outside docker.
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true  # required for some metrics

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.2-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

  # immich-cli:
  #   container_name: immich_cli
  #   image: ghcr.io/immich-app/immich-cli:latest
  #   env_file:
  #     - .env
  #   environment:
  #     IMMICH_INSTANCE_URL: https://192.168.2.214:2283
  #     IMMICH_API_KEY: "{{ vault_immich_cli_api_key }}"
  #   entrypoint: [ "sleep", "infinity" ]  # So you can exec into it and run multiple commands
  #   depends_on:
  #     - immich-server
  #   restart: unless-stopped

  disk-status-exporter:
    image: ghcr.io/johnmathews/disk_status_exporter:latest
    container_name: disk_status_exporter
    restart: always
    ports:
      - "9635:9635"
    volumes:
      - /dev:/dev:ro
    privileged: true  # recommended to access /dev/sdX and run smartctl

volumes:
  model-cache:
