# proxmox_node/files/docker-compose.yml

---

services:

  # node exporter is running outside docker.
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true  # required for some metrics

  disk-status-exporter:
    image: ghcr.io/johnmathews/disk_status_exporter:latest
    container_name: disk_status_exporter
    restart: always
    ports:
      - "9635:9635"
    volumes:
      - /dev:/dev:ro
    privileged: true  # recommended to access /dev/sdX and run smartctl
