open_webui_lxc_pgid: 1001

open_webui_lxc_app_name: "open-webui"

# Docker image versions
open_webui_lxc_cadvisor_version: "{{ sidecar_cadvisor_version }}"
open_webui_lxc_alloy_version: "{{ sidecar_alloy_version }}"
open_webui_lxc_node_exporter_version: "{{ sidecar_node_exporter_version }}"
