pgid: 1001

app_name: "open-webui"

smb_username: smb_user

smb_server: 192.168.2.104

# Docker image versions
cadvisor_version: "v0.49.1"
alloy_version: "v1.5.1"
node_exporter_version: "v1.8.2"

smb_shares:
  - name: paperless
    target: /mnt/paperless
