# jellyfin_lxc/files/docker-compose.yml

---

services:

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    environment:
      LOKI_WRITE_ENDPOINT: "http://192.168.2.106:3100/loki/api/v1/push"
      NODE_HOSTNAME: "jellyfin"
      LOG_LEVEL: "warn"
    volumes:
      # config 
      - ./alloy:/etc/alloy:ro 
      # docker 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # journalctl  
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    mem_limit: 8g
    mem_reservation: 4g
    # user: "1001:1001" # this breaks volume mounts
    ports:
      - "8096:8096"
    environment:
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=http://192.168.2.110:8096
      - PUID=1001
      - PGID=1001
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/apps/jellyfin/plugins/tubearchivist_metadata:/config/plugins/TubeArchivistMetadataKids_1.3.19.0
      - /srv/apps/jellyfin/appdata:/config
      - /srv/apps/jellyfin/cache:/cache
      - /mnt/nfs/library:/library # kids shows, family movies, etc
      - /mnt/nfs/media:/media # youtube videos, photography videos
      - /mnt/nfs/youtube-kids:/youtube-kids # tubearchivist lib must be readonly
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    privileged: true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true  # required for some metrics

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/textfile'
    network_mode: host
    ports:
      - "9100:9100"
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
      - '/var/lib/node_exporter/textfile_collector:/textfile:ro'

