[proxmox]
pve ansible_host=192.168.2.214 ansible_user=root ansible_ssh_private_key_file=~/.ssh/john_macbook

[media]
media-vm ansible_host=192.168.2.105 ansible_user=john ansible_ssh_private_key_file=~/.ssh/john_macbook

[infra]
infra-vm ansible_host=192.168.2.106 ansible_user=john ansible_ssh_private_key_file=~/.ssh/john_macbook

[nas]
nas_vm ansible_host=192.168.2.104 ansible_user=truenas_admin ansible_ssh_private_key_file=~/.ssh/john_macbook

[keys]
key_server ansible_host=192.168.2.201 ansible_user=john ansible_ssh_private_key_file=~/.ssh/john_macbook




; unused...

; [tunnel]
; cloudflared

; [traefik]
; traefik_lxc ansible_host=192.168.2.101 ansible_user=root ansible_ssh_private_key_file=~/.ssh/john_macbook
