[all:vars]
ansible_ssh_private_key_file=~/.ssh/john_macbook

[proxmox]
pve ansible_host=192.168.2.214 ansible_user=root

[media]
media-vm ansible_host=192.168.2.105 ansible_user=john

[infra]
infra-vm ansible_host=192.168.2.106 ansible_user=john

[nas]
nas_vm ansible_host=192.168.2.104 ansible_user=truenas_admin

[keys]
key_server ansible_host=192.168.2.201 ansible_user=john

[traefik]
traefik_lxc ansible_host=192.168.2.108 ansible_user=root

[immich]
immich_lxc ansible_host=192.168.2.113 ansible_user=root

[tubearchivist]
tubearchivist_lxc ansible_host=192.168.2.116 ansible_user=root

[prometheus]
prometheus_lxc ansible_host=192.168.2.115 ansible_user=root

[paperless]
paperless_lxc ansible_host=192.168.2.117 ansible_user=root

[jellyfin]
jellyfin_lxc ansible_host=192.168.2.110 ansible_user=root

[open_webui]
open_webui_lxc ansible_host=192.168.2.119 ansible_user=root

[atuin_clients:children]
proxmox
media
infra
keys
traefik
immich
jellyfin


[nfs_clients:children]
media
immich
jellyfin
tubearchivist
paperless

[share_drive_clients:children]
media
immich
jellyfin
tubearchivist
paperless
