# requirements.yml

collections:
  - name: community.general
    version: ">=7.4.7" 
  - name: community.proxmox

roles:
  - name: geerlingguy.pip
  - name: geerlingguy.docker
  - name: bellackn.homelab
