# site.yml
---

- name: Proxmox VE Configuration
  hosts: proxmox
  gather_facts: true
  become: true

  vars:
    email_address: "john@johnmathews.is"

  roles:
    - role: pve-repos
      tags: common
    - role: common
      tags: common
    - role: zram
      tags: common
    - role: postfix
      tags: common

- name: TrueNAS VM
  hosts: proxmox
  gather_facts: true
  become: true

  vars:
    email_address: "john@johnmathews.is"

  roles:
    - role: upload_iso
      tags: upload_iso
    - role: truenas_vm
      tags: truenas

- name: Upload Cloud Image
  hosts: proxmox
  gather_facts: false
  roles:
    - role: upload_cloud_image
      tags: cloud_image

- name: Media VM 
  hosts: media
  gather_facts: false
  become: true

  roles:
    - role: media_vm
      tags: media
    - role: media_stack
      tags: media_stack

- name: Provision and configure Cloudflared LXC container
  hosts: proxmox
  roles:
    - cloudflared_lxc
