# site.yml
---

- name: Proxmox VE Configuration
  hosts: proxmox
  gather_facts: false
  become: true

  vars:
    email_address: "john@johnmathews.is"

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: pve-repos
      tags: common
    - role: common
      tags: common
    - role: zram
      tags: common
    - role: postfix
      tags: common

- name: TrueNAS VM
  hosts: proxmox
  gather_facts: false
  become: true

  vars:
    email_address: "john@johnmathews.is"

  roles:
    - role: upload_iso
      tags: upload_iso
    - role: truenas_vm
      tags: truenas

- name: Configure Media Stack
  hosts: media
  become: true
  gather_facts: true

  roles:
    - role: upload_cloud_image
      tags: cloud_image
    - role: media_vm
      tags: media
    - role: media_stack
      tags: media_stack
