TZ: Europe/Amsterdam

proxmox_api_user: "api@pve"

smb_proxmox_username: proxmox_smb_user
smb_server: 192.168.2.104
smb_shares:
  - name: library 
    target: /mnt/media/library
  - name: media 
    target: /mnt/media/media
  - name: immich 
    target: /mnt/immich
