# tasks/docker-jellyfin.yml
# /srv/jellyfin/config

---


- name: Download Docker GPG key (Bookworm-compatible)
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker Compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present

- name: Ensure Docker Compose directory exists
  ansible.builtin.file:
    path: /srv/apps
    state: directory


- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /srv/apps/alloy

- name: Upload config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  loop:
    - alloy:
      src: files/config.alloy
      dest: /srv/apps/alloy/config.alloy
  become: true
  tags: alloy
  notify:
    - Restart alloy

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/apps/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  tags: portainer

- name: Deploy .env file template
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /srv/apps/.env
    owner: root
    group: root
    mode: '0644'
  tags: portainer

- name: Start apps using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /srv/apps
  tags: portainer
