# proxmox_node/tasks/hdparm.yml

---

- name: Ensure hdparm is installed
  ansible.builtin.package:
    name: hdparm
    state: present

- name: Configure hdparm for PBS disk
  ansible.builtin.blockinfile:
    path: /etc/hdparm.conf
    create: yes
    block: |
      {{ hdparm_disk_id }} {
          spindown_time = {{ hdparm_spindown }}
          apm = {{ hdparm_apm }}
          write_cache = on
          acoustic_management = 128
      }
