# proxmox_node/tasks/main.yml

---


- name: Configure DNS resolvers
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  tags: dns

- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: docker, metrics

- name: Install libraries and dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - smartmontools
      - sysstat
      - cifs-utils
    state: present
  tags: docker, metrics

- name: Ensure keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Set up IPMI exporter
  ansible.builtin.import_tasks: ipmi_exporter.yml
  tags: metrics

# - name: Set up Node exporter
# use docker service instead
#   import_tasks: node_exporter.yml
#   tags: [metrics]

- name: Set up Proxmox exporter
  ansible.builtin.import_tasks: pve_exporter.yml
  tags: metrics

- name: Set up docker
  ansible.builtin.import_tasks: docker-apps.yml
  tags: docker

# smartctl disk metrics
- name: Setup smartctl_exporter
  ansible.builtin.import_tasks: smartctl.yml
  tags: metrics, smartctl

# hd-idle disk spindown settings
- name: Setup hd-idle
  ansible.builtin.import_tasks: hd-idle.yml
  tags: hd-idle

# iGPU metrics
- name: Install radeontop metrics exporter
  ansible.builtin.import_tasks: radeontop-exporter.yml
  tags: metrics, media, radeontop

# for homepage
- name: Install glances
  ansible.builtin.import_tasks: glances.yml
  tags: [metrics, glances]

- name: Setup hdparm for HDD power management
  ansible.builtin.import_tasks: hdparm.yml
  tags: [hdd, hdparm]

# NUT
- name: Setup NUT
  ansible.builtin.import_tasks: nut.yml
  tags: [nut]
