# roles/jellyfin_lxc/tasks/main.yml

---

- name: Ensure cifs-utils is installed
  ansible.builtin.apt:
    name: cifs-utils
    state: present
    update_cache: yes

- name: Create directory for SMB credentials
  ansible.builtin.file:
    path: /etc/smb
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Create SMB credentials file
  ansible.builtin.copy:
    dest: "/etc/smb/.smbcredentials"
    content: |
      username={{ smb_proxmox_username }}
      password={{ vault_smb_proxmox_password }}
    owner: root
    group: root
    mode: '0600'

- name: Persist SMB mount in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^//{{ smb_server }}/{{ item.name }}[ \t]+'
    line: "//{{ smb_server }}/{{ item.name }} {{ item.target }} cifs credentials=/etc/smb/.smbcredentials,iocharset=utf8,noperm,nofail,noauto,x-systemd.automount,x-systemd.device-timeout=10,_netdev,vers=3.0 0 0"
    state: present
    create: yes
  loop: "{{ smb_shares }}"

- name: Create local mount point
  ansible.builtin.file:
    path: "{{ item.target }}"
    state: directory
    mode: '0755'
  loop: "{{ smb_shares }}"

- name: Mount SMB shares
  mount:
    path: "{{ item.target }}"
    src: "//{{ smb_server }}/{{ item.name }}"
    fstype: cifs
    opts: credentials=/etc/smb/.smbcredentials,iocharset=utf8,noperm,nofail,vers=3.0
    state: mounted
  loop: "{{ smb_shares }}"

- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /srv/apps/tubearchiver

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: /templates/docker-compose.yml.j2
    dest: /srv/apps/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker Compose stack

- name: Include Atuin setup
  ansible.builtin.include_role:
    name: atuin
