- name: Restart all containers
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: always
    pull: never
    dependencies: true
  become: false

- name: Restart paperless
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - paperless-db
      - paperless-webserver
      - paperless-broker
    state: present
    recreate: always
    pull: never
    dependencies: true
  become: false

- name: Restart alloy
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - alloy
    state: present
    recreate: always
    pull: never
    dependencies: true
  become: false

- name: Restart sleep-hours timers
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - docker-sleep@pause.timer
    - docker-sleep@unpause.timer

- name: Restart library
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - library-db
      - library-migrate
      - library-api
      - library-worker
    state: present
    recreate: always
    pull: never
    dependencies: true
  become: false
