---

- name: Restart Docker Compose stack
  ansible.builtin.command: docker compose -f /srv/apps/docker-compose.yml up -d
  args:
    chdir: /srv/apps

- name: Update containers
  command: docker compose pull
  args:
    chdir: /srv/apps
