# infra_vm/tasks/docserver.yml

- name: Ensure docserver directories exists
  ansible.builtin.file:
    path: /srv/infra/docserver/config
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0755'
  notify: Restart docserver
  tags: docserver, documentation

- name: Template docserver sources.yaml
  ansible.builtin.template:
    src: docserver-sources.yml.j2
    dest: /srv/infra/docserver/config/sources.yaml
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  notify: Restart docserver
  tags: docserver, documentation

- name: Template docserver document-types.yaml
  ansible.builtin.template:
    src: docserver-doctypes.yml.j2
    dest: /srv/infra/docserver/config/document-types.yaml
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  notify: Restart docserver
  tags: docserver, documentation
