# infra_vm/tasks/homepage.yml

---

- name: Ensure homepage config directory exists
  file:
    path: /srv/infra/homepage/config
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0755'
  notify: Restart homepage container

- name: Upload homepage config files to infra VM
  copy:
    src: "{{ item }}"
    dest: "/srv/infra/homepage/config/{{ item | basename }}"
    owner: "{{docker_user }}"
    group: "{{docker_user }}"
    mode: '0644'
  with_fileglob:
    - "files/homepage_config/*"
  register: homepage_config_uploads
  become: true
  notify: Restart homepage container

- name: Template homepage services.yaml
  template:
    src: homepage/services.yaml.j2
    dest: /srv/infra/homepage/config/services.yaml
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  notify: Restart homepage container

