# infra_vm/tasks/main.yml

---

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
    state: present

- name: Install pipx
  apt:
    name: pipx
    state: present

- name: Ensure pipx binary path is available
  shell: |
    pipx ensurepath
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ docker_user }}/.local/bin"
  become_user: "{{ docker_user }}"

- name: Install uv using pipx
  become: true
  become_user: "{{ docker_user }}"
  shell: |
    pipx install uv
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ docker_user }}/.local/bin"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Create Docker Compose directory
  file:
    path: /opt/infra_stack
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'

- name: Ensure grafana custom config directory exists
  file:
    path: /opt/infra_stack/custom
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy custom grafana.ini
  template:
    src: grafana/grafana.ini.j2
    dest: /opt/infra_stack/custom/grafana.ini
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana container

- name: Ensure loki config directory exists
  file:
    path: /opt/infra_stack/loki
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure loki config subdirs exist
  file:
    path: /opt/infra_stack/loki/{{item}}
    state: directory
    owner: 10001
    group: 10001
    mode: '0755'
    recurse: yes
  loop:
    - var/compactor
    - chunks
    - index
    - cache
    - rules
    - rules-temp
    - wal

- name: Deploy custom loki config
  template:
    src: files/loki/loki-config.yml
    dest: /opt/infra_stack/loki/loki/loki-config.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart loki container

- name: Ensure promtail config directory exists
  file:
    path: /opt/infra_stack/promtail
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy custom promtail config
  template:
    src: files/promtail/promtail-config.yml
    dest: /opt/infra_stack/promtail/promtail-config.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart promtail container

- name: Template Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/infra_stack/docker-compose.yml
    owner: "{{ docker_user }}"
    group: docker
    mode: '0644'
  notify: Apply updated Docker Compose stack


- name: Launch containers
  command: docker compose up -d
  args:
    chdir: /opt/infra_stack

- name: Create Prometheus config directory
  file:
    path: /opt/infra_stack/prometheus
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'

- name: Include config tasks for docker services (prometheus and homepage)
  import_tasks: services_config.yml
  tags: [config]
