# infra_vm/tasks/main.yml

---

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - qemu-guest-agent
    state: present
    update_cache: yes

- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
    state: present

- name: Install pipx
  apt:
    name: pipx
    state: present

- name: Ensure pipx binary path is available
  shell: |
    pipx ensurepath
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ docker_user }}/.local/bin"
  become_user: "{{ docker_user }}"

- name: Install uv using pipx
  become: true
  become_user: "{{ docker_user }}"
  shell: |
    pipx install uv
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ docker_user }}/.local/bin"
  tags: [grafana]

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [grafana]

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present
  tags: [grafana]

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  tags: [grafana]

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  tags: [grafana]

- name: Create Docker Compose directory
  file:
    path: /srv/infra
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'
  tags: [grafana]

- name: Ensure grafana custom config directory exists
  file:
    path: /srv/infra/grafana/config
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: [grafana]

- name: Template Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /srv/infra/docker-compose.yml
    owner: "{{ docker_user }}"
    group: docker
    mode: '0644'
  notify: Apply updated Docker Compose stack
  tags: [grafana]

- name: Upload .env file from template
  ansible.builtin.template:
    src: templates/.env.j2 
    dest: /srv/infra/.env  
    owner: "{{ docker_user }}"
    group: docker 
    mode: '0600'

- name: Include file-browser tasks 
  import_tasks: file-browser.yml
  tags: [config]

- name: Include homepage tasks
  import_tasks: homepage.yml
  tags: [config]

- name: Update containers
  command: docker compose pull
  args:
    chdir: /srv/infra
  tags: [grafana]

- name: Launch containers
  command: docker compose up -d
  args:
    chdir: /srv/infra
  tags: [grafana]

