# infra_vm/tasks/main.yml

---

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - qemu-guest-agent
    state: present
    update_cache: yes

- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
      - python-is-python3
    state: present

- name: Install pipx
  apt:
    name: pipx
    state: present

- name: Ensure pipx binary path is available
  shell: |
    pipx ensurepath
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ docker_user }}/.local/bin"
  become_user: "{{ docker_user }}"

- name: Install uv using pipx
  become: true
  become_user: "{{ docker_user }}"
  shell: |
    pipx install uv
  environment:
    PATH: "{{ ansible_env.PATH }}:/home/{{ docker_user }}/.local/bin"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Create Docker Compose directory
  file:
    path: /srv/infra
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'

# - import_tasks: mount-smb.yml
#   tags: [mount, smb]

- name: Ensure grafana custom config directory exists
  file:
    path: /srv/infra/grafana/config
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy custom grafana.ini
  template:
    src: grafana/grafana.ini.j2
    dest: /srv/infra/grafana/config/grafana.ini
    owner: root
    group: root
    mode: '0644'
  notify: Restart Grafana container

- name: Template Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /srv/infra/docker-compose.yml
    owner: "{{ docker_user }}"
    group: docker
    mode: '0644'
  notify: Apply updated Docker Compose stack

- name: Create Prometheus config directory
  file:
    path: /srv/infra/prometheus
    state: directory
    owner: "{{ docker_user }}"
    group: docker
    mode: '0755'

- name: Ensure Prometheus data directory is owned by UID/GID 65534
  ansible.builtin.file:
    path: /srv/infra/prometheus/data
    state: directory
    recurse: yes
    owner: "65534"
    group: "65534"

- name: Ensure ntfy cache directory exists with correct ownership
  file:
    path: /var/cache/ntfy
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Ensure ntfy config directory exists with correct ownership
  file:
    path: /etc/ntfy
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Set permissions of ntfy cache directory
  ansible.builtin.command: chown -R 1000:1000 /var/cache/ntfy
  become: true

- name: Set permissions of ntfy config directory
  ansible.builtin.command: chown -R 1000:1000 /etc/ntfy
  become: true

- name: Ensure filebrowser config directory exists with correct ownership
  ansible.builtin.file:
    path: /srv/infra/filebrowser/config
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
    recurse: yes
  notify: Restart filebrowser container

- name: Ensure /database dir exists with proper ownership
  ansible.builtin.file:
    path: /srv/infra/filebrowser/config/database
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'

- name: Recursively set permissions on files in filebrowser config directory
  ansible.builtin.find:
    paths: /srv/infra/filebrowser/config
    file_type: file
  register: filebrowser_files

- name: Set file mode to 0644
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ filebrowser_files.files }}"
  notify: Restart filebrowser container

- name: Recursively set permissions on directories in filebrowser config directory
  ansible.builtin.find:
    paths: /srv/infra/filebrowser/config
    file_type: directory
  register: filebrowser_dirs

- name: Set directory mode to 0755
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0755'
  loop: "{{ filebrowser_dirs.files }}"
  notify: Restart filebrowser container

- name: Update containers
  command: docker compose pull
  args:
    chdir: /srv/infra

- name: Launch containers
  command: docker compose up -d
  args:
    chdir: /srv/infra

- name: Include config tasks for docker services (prometheus and homepage)
  import_tasks: services_config.yml
  tags: [config]
