# infra_vm/tasks/mkdocs.yml

---

- name: Ensure mkdocs docs directory exists
  file:
    path: /srv/infra/mkdocs/docs
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0755'
  notify: restart mkdocs

- name: Template mkdocs.yml
  template:
    src: mkdocs.yml.j2
    dest: /srv/infra/mkdocs/mkdocs.yml
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  notify: restart mkdocs

- name: Copy project markdown docs into mkdocs docs dir
  copy:
    src: ../documentation/
    dest: /srv/infra/mkdocs/docs/
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  notify: restart mkdocs
