# roles/infra_vm/tasks/mount-smb.yml

---

- name: Create mount points for SMB shares
  file:
    path: "{{ item.target }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ smb_shares }}"

- name: Ensure credentials file exists for SMB mount
  copy:
    dest: /etc/smbcredentials_truenas_logs
    content: |
      username={{ smb_infra_vm_username }}
      password={{ vault_smb_infra_vm_password }}
    owner: root
    group: root
    mode: "0600"

- name: Ensure /etc/fstab entries for SMB shares
  lineinfile:
    path: /etc/fstab
    line: "//{{ smb_server }}/{{ item.name }} {{ item.target }} cifs credentials=/etc/smbcredentials_truenas_logs,vers=3.0,rw,uid=1000,gid=1000 0 0"
    create: yes
    state: present
  loop: "{{ smb_shares }}"

- name: Mount all SMB shares now
  mount:
    path: "{{ item.target }}"
    src: "//{{ smb_server }}/{{ item.name }}"
    fstype: cifs
    opts: "credentials=/etc/smbcredentials_truenas_logs,vers=3.0,rw,uid=1000,gid=1000"
    state: mounted
  loop: "{{ smb_shares }}"
