# infra_vm/tasks/services_config.yml

---

- name: Template Prometheus config
  template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ docker_compose_dir }}/prometheus/prometheus.yml"
    owner: "{{ docker_user }}"
    group: docker
    mode: '0644'
  notify: Restart Prometheus container

- name: Ensure homepage config directory exists
  file:
    path: /srv/infra/homepage/config
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0755'

- name: Upload homepage config files to infra VM
  copy:
    src: "{{ item }}"
    dest: "/srv/infra/homepage/config/{{ item | basename }}"
    owner: "{{docker_user }}"
    group: "{{docker_user }}"
    mode: '0644'
  with_fileglob:
    - "files/homepage_config/*"
  register: homepage_config_uploads
  become: true
  notify: Restart homepage container

- name: Template Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: docker
    mode: '0644'
  notify: Restart homepage container

- name: Template homepage services.yaml
  template:
    src: homepage/services.yaml.j2
    dest: /srv/infra/homepage/config/services.yaml
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0644'
  notify: Restart homepage container
