# proxmox_node/tasks/main.yml

---


- name: Ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install libraries and dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - smartmontools 
      - sysstat
    state: present
  tags: [metrics]

- name: Ensure keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Set up IPMI exporter
  import_tasks: ipmi_exporter.yml
  tags: [metrics]

- name: Set up Node exporter
  import_tasks: node_exporter.yml
  tags: [metrics]

- name: Set up Proxmox exporter
  import_tasks: pve_exporter.yml
  tags: [metrics]

- name: Set up docker 
  import_tasks: docker-apps.yml
  tags: [docker]

# smartctl disk metrics
- name: Setup smartctl_exporter
  import_tasks: smartctl.yml
  tags: [metrics, smartctl]

# hd-idle disk spindown settings
- name: Setup hd-idle
  import_tasks: hd-idle.yml
  tags: [hd-idle]

# iGPU metrics
- name: Install radeontop metrics exporter
  import_tasks: radeontop-exporter.yml
  tags: [metrics, media, radeontop]

# for homepage
- name: Install glances
  import_tasks: glances.yml
  tags: [metrics, glances]
 
- name: Setup hdparm for HDD power management 
  import_tasks: hdparm.yml
  tags: [hdd, hdparm]

# NUT 
- name: Setup NUT 
  import_tasks: nut.yml
  tags: [nut]
