---

- name: Create john user
  ansible.builtin.user:
    name: john
    shell: /bin/bash
    create_home: true
    state: present

- name: Create base app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ docker_compose_dir }}"
    - /srv/apps/alloy

- name: Upload alloy config
  ansible.builtin.copy:
    src: templates/config.alloy
    dest: /srv/apps/alloy/config.alloy
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  become: true
  tags: alloy
  notify:
    - restart alloy

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
  tags: docker
  notify:
    - restart all containers
