# roles/immich_lxc/tasks/main.yml

- name: Ensure cifs-utils is installed
  ansible.builtin.apt:
    name: cifs-utils
    state: present
    update_cache: true

# ensure CIFS tools are present (inside the container)
- name: Ensure CIFS client packages are installed
  ansible.builtin.apt:
    name: cifs-utils
    state: present
  become: true
  tags: cifs

- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /srv/apps/immich/
    - /srv/apps/immich/postgres
    - /srv/apps/alloy
  tags: alloy, immich

- name: Deploy .env file template
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /srv/apps/.env
    owner: root
    group: root
    mode: '0644'
  tags: docker

- name: Deploy immich api file
  ansible.builtin.template:
    src: files/immich_api_key.secret
    dest: /srv/apps/immich/immich_api_key.secret
    owner: root
    group: root
    mode: '0644'
  tags: docker

- name: Upload alloy config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  loop:
    - alloy:
      src: templates/config.alloy
      dest: /srv/apps/alloy/config.alloy
  become: true
  tags: alloy
  notify: Restart alloy

- name: Template Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/apps/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart docker compose stack
  tags: docker

- name: Set Immich environment variables
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  become: true
  loop:
    - {key: IMMICH_API_KEY, value: "{{ vault_immich_media_vm_api_key }}"}
    - {key: IMMICH_LIBRARY_ID, value: "{{ vault_immich_reference_library_id }}"}
    - {key: IMMICH_API_URL, value: "{{ vault_immich_api_url }}"}
    - {key: IMMICH_SHARE_USER, value: "John"}
    - {key: PUSHOVER_USER_KEY, value: "{{ vault_pushover_user_key }}"}
    - {key: PUSHOVER_APP_TOKEN, value: "{{ vault_pushover_media_vm_app_api_token }}"}
  tags: immich, pushover

- name: Fix facebook-albums permissions (one-time)
  ansible.builtin.import_tasks: fix_facebook_albums_permissions.yml
  when: fix_facebook_albums_perms | default(false) | bool
  tags: fix_permissions
