# roles/immich_lxc/tasks/main.yml

---

- name: Ensure cifs-utils is installed
  ansible.builtin.apt:
    name: cifs-utils
    state: present
    update_cache: yes

# ensure CIFS tools are present (inside the container)
- name: Ensure CIFS client packages are installed
  apt:
    name: cifs-utils
    state: present
  become: true
  tags: cifs

- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /srv/apps/immich/
    - /srv/apps/immich/postgres
    - /srv/apps/alloy
  tags: [docker, alloy] 

- name: Deploy .env file template 
  template:
    src: templates/.env.j2 
    dest: /srv/apps/.env
    owner: root
    group: root
    mode: '0644'
  tags: [docker] 

- name: Upload alloy config files 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  loop:
    - alloy:
      src: templates/config.alloy
      dest: /srv/apps/alloy/config.alloy 
  become: true
  tags: [docker, alloy] 
  notify: 
    - Restart Alloy

- name: Copy Docker Compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /srv/apps/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker Compose stack
  tags: [docker, alloy] 
