# roles/truenas_vm/tasks/main.yml
---
- name: Create TrueNAS VM
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ vault_proxmox_password }}"
    api_host: "{{ inventory_hostname }}"
    node: pve
    vmid: 200
    name: truenas
    cores: 4
    memory: 12288
    scsihw: virtio-scsi-pci
    boot: order=scsi0;ide2
    bootdisk: scsi0
    ide:
      ide2: media=cdrom,volume=local:iso/TrueNAS-SCALE-24.10.2.1.iso
    scsi:
      scsi0: size=16G,storage=local-lvm
    net:
      net0: model=virtio,bridge=vmbr0
    ostype: l26
    onboot: yes
    state: present
  delegate_to: localhost
  become: false
