# roles/jellyfin_lxc/tasks/main.yml

---

- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ docker_compose_dir }}/alloy"
    - "{{ docker_compose_dir }}/prometheus"
    - "{{ docker_compose_dir }}/prometheus/rules"
  tags: prometheus

- name: Ensure Prometheus data directory is owned by UID/GID 65534
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/prometheus/data"
    state: directory
    recurse: yes
    owner: "65534"
    group: "65534"
  tags: prometheus

- name: Template Prometheus config
  template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ docker_compose_dir }}/prometheus/prometheus.yml"
    owner: root
    group: docker
    mode: '0644'
  notify: restart prometheus
  tags: prometheus

- name: Copy UPS Prometheus rules
  ansible.builtin.template:
    src: templates/prometheus/rules.yml.j2
    dest: "{{ docker_compose_dir }}/prometheus/rules/rules.yml"
    owner: root
    group: docker
    mode: '0644'
  notify: restart prometheus
  tags: prometheus

- name: Upload alloy config files 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  loop:
    - alloy:
      src: templates/config.alloy
      dest: /srv/apps/alloy/config.alloy 
  become: true
  tags: alloy
  notify: 
    - restart alloy

# Copy environment and compose files
- name: Copy docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /srv/apps/docker-compose.yml
    mode: '0644'
    owner: root
    group: root
  tags: docker
  notify: 
    - restart docker compose stack
