# media_vm/defaults/main.yml

cloud_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img

cloud_image_dir: "{{ playbook_dir }}/cloud-images"
cloud_image_base_filename: "jammy-server-cloudimg-amd64.img"
cloud_image_filename: "jammy-server-cloudimg-amd64.raw"

proxmox_api_host: "{{ hostvars['pve']['ansible_host'] }}"



media_stack_user: media
media_stack_group: media
media_stack_base_dir: /opt/media-stack
media_stack_data_dir: /opt/media-stack/config

media_stack_services:
  jellyfin_port: 8096
  qbittorrent_port: 8080
  sonarr_port: 8989
  radarr_port: 7878
  jackett_port: 9117
  bazarr_port: 6767

