# media_vm/defaults/main.yml

# defaults/main.yml has the lowest priority. host_vars/media-vm.yml has highest priority.

# Changing this will require you to `cd /src/media && docker compose logs qbittorrent` 
# to get the new temp password. Then in qBittorrent set the old password again
reset_qbittorrent_config: false


TZ: Europe/Amsterdam

proxmox_api_host: "{{ hostvars['pve']['ansible_host'] }}"

media_stack_mount_dir: /mnt/media
media_stack_base_dir: /srv/media
media_stack_config_dir: /srv/media/config


media_stack_user: john
media_stack_group: john

qbittorrent_uid: 1001
qbittorrent_gid: 1001
puid: 1001
guid: 1001

qbittorrent_password_hash: 16c5e9c9b842bd6bf78aafa66643304e0cfe2586

media_stack_services:
  jellyfin_port: 8096
  qbittorrent_port: 8080
  sonarr_port: 8989
  radarr_port: 7878
  jackett_port: 9117
  bazarr_port: 6767

media_stack_users:
  jellyfin:
    username: john
  qbittorrent:
    username: admin
  sonarr:
    username: john
  radarr:
    username: john
  bazarr:
    username: john
  jackett:
    username: john
  filebrowser:
    username: john

smb_media_vm_username: media_vm
smb_server: 192.168.2.104
smb_shares:
  - name: library 
    target: /mnt/media/library
  - name: media 
    target: /mnt/media/media
