# roles/infra_vm/files/promtail/promtail-config.yml

---

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    pipeline_stages:
      - docker: {}
      - labels:
          container: ""
          compose_service: ""

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'

  - job_name: truenas_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: truenas
          host: truenas
          __path__: /mnt/truenas/logs/**/*.log  # Only .log files, recursive
    pipeline_stages:
      - match:
          selector: '{job="truenas"}'
          stages:
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2}'  # e.g., starts with timestamp
                max_wait_time: 3s
            - drop:
                expression: '.*[^\x09\x0A\x0D\x20-\x7E].*'
            - drop:
                expression: '.*\.gz$'
            - drop:
                expression: '.*\.\d+$'
            - regex:
                expression: '.*/(?P<filename>[^/]+\.log)$'
            - regex:
                expression: '(?i)(?P<level>info|error|warn|warning|debug|notice|crit|critical)'
            - template:
                source: level
                template: '{% raw %}{{ .Value | ToLower }}{% endraw %}'
            - labels:
                filename: filename
                level: level
