---

- name: Update containers
  command: docker compose pull
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart all containers 
  ansible.builtin.command: docker compose restart
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart qbittorrent container
  command: docker compose restart qbittorrent
  args:
    chdir: "{{ docker_compose_dir }}"
