TZ: Europe/Amsterdam

proxmox_api_user: "api@pve"
docker_compose_dir: "/srv/apps"
docker_user: john

puid: 1001
guid: 1001
pgid: 1001

base_dir: /srv/media

smb_username: smb_user

smb_server: 192.168.2.104
smb_shares:
  - name: library
    target: /mnt/library

truenas_ip: "192.168.2.104"
nfs_export: "/mnt/tank/library"
nfs_mountpoint: "/mnt/nfs/library"

# NFS options tuned for NFSv4.2 over TCP. Adjust as needed:
nfs_opts: "vers=4.2,proto=tcp,soft,timeo=5,retrans=2,_netdev,nofail"
