TZ: Europe/Amsterdam

proxmox_api_user: "api@pve"

# smb_media_vm_username: media_vm
smb_username: smb_user

smb_server: 192.168.2.104
smb_shares:
  - name: library 
    target: /mnt/media/library
  - name: media 
    target: /mnt/media/media
  - name: youtube-kids 
    target: /mnt/youtube-kids

