TZ: Europe/Amsterdam
cloudflared_config_dir: /etc/cloudflared
cloudflared_tunnel_name: home-server
cloudflared_tunnel_id: e1e3b9c4-789a-4ad3-adff-a0c71bff1122
cloudflared_account_id: "{{ vault_cloudflared_account_id }}"
cloudflared_api_token: "{{ vault_cloudflared_api_token }}"
