TZ: Europe/Amsterdam
proxmox_api_user: "api@pve"
docker_compose_dir: "/srv/apps"
docker_user: john
puid: 1001
guid: 1001
pgid: 1001
# sleep docker containers during quiet hours and pause uptime-kuma monitors
uptime_kuma_url: "http://192.168.2.106:3001"
uptime_kuma_user: "john"
