pgid: 1001

# Docker image versions
paperless_version: "2.14.7"
node_exporter_version: "v1.8.2"
alloy_version: "v1.5.1"
cadvisor_version: "v0.49.1"

# SMB is NOT necessary. The paperless instance itself connects the the paperless datastore via NFS.
# other clients, phones, laptops etc connect to paperless datastore via SMB which is a trueNAS dataset and independent of the paperless service.
smb_media_vm_username: media_vm
smb_server: 192.168.2.104
smb_opts_items:
  - credentials=/etc/smb-media-credentials
  - uid={{ puid }}
  - gid={{ guid }}
  - file_mode=0664
  - dir_mode=0775
  - vers=3.1.1
  - sec=ntlmssp
  - serverino
  - _netdev
  - nofail
  - iocharset=utf8
  - x-systemd.automount
  - x-systemd.idle-timeout=60s
  - x-systemd.mount-timeout=30s
smb_opts: "{{ smb_opts_items | join(',') }}"

# Library (paperless replacement; ghcr image tag = git commit sha of release)
library_version: "fd9c27676ab7486dffe1327bc61bff4dc527e4bf"
