TZ: Europe/Amsterdam

proxmox_api_user: "api@pve"
docker_compose_dir: "/srv/apps"
docker_user: john

puid: 1001
guid: 1001
pgid: 1001

# smb_username: smb_user
# smb_server: 192.168.2.104
# smb_shares:
#   - name: paperless
#     target: /mnt/paperless

nfs_opts_items:
  - _netdev
  - hard
  - nofail
  - proto=tcp
  - retrans=2
  - timeo=150
  - vers=4.2
  - x-systemd.automount
  - x-systemd.idle-timeout=60s

nfs_opts: "{{ nfs_opts_items | join(',') }}"

