####################################
# Grafana configuration
####################################

[server]
http_addr =
http_port = 3000
domain = charts.{{ primary_domain_name }}
root_url = https://charts.{{ primary_domain_name }}/
enforce_domain = false
serve_from_sub_path = false
enable_gzip = true

[security]
allow_embedding = true
cookie_secure = true
cookie_samesite = none

[users]
allow_sign_up = false

[auth.anonymous]
enabled = true
org_role = Viewer

[database]
type = sqlite3
path = /var/lib/grafana/grafana.db
wal = true

[log]
mode = console
level = warn

[log.filters]
# Reduce noise from authentication attempts when viewing anonymously
authn = error
context = error

[feature_toggles]
enable = publicDashboards

[analytics]
reporting_enabled = false
check_for_updates = false
check_for_plugin_updates = false
feedback_links_enabled = false

