# proxmox_node/defaults/main.yml

---

proxmox_api_user: "api@pve"

# iGPU
radeontop_exporter_path: /usr/local/bin/radeontop-exporter.py

# ipmi
ipmi_exporter_version: "1.10.0"
ipmi_exporter_install_dir: "/opt/ipmi_exporter"
ipmi_exporter_listen_port: 9290

# node_exporter
node_exporter_version: "1.9.1"
node_exporter_install_dir: "/opt/node_exporter"
node_exporter_listen_port: 9100

#smartmon
smartmon_exporter_version: "0.11.0"
smartmon_exporter_install_dir: "/opt/smartmon_exporter"
smartmon_exporter_listen_port: 9633

# smartctl
smartctl_exporter_enabled: true
smartctl_exporter_smartctl_device_include: ""
smartctl_exporter_smartctl_rescan: "10m"
smartctl_exporter_smartctl_interval: "30s"
smartctl_exporter_system_user: root
smartctl_exporter_system_group: root

# pve_exporter
pve_exporter_version: "3.5.3"
pve_exporter_install_dir: "/opt/pve_exporter"
pve_exporter_listen_port: 9221

# backup disk set spindown using hdparm service.
# hdparm_disk_id: /dev/disk/by-id/ata-ST3000DM007-1WY10G_ZFN1TN5X # this is the PBS HDD.
hdparm_disk_id: /dev/sda # this is the PBS HDD.
hdparm_apm: 128
#12: 1 minute, 120: 10 minutes, 241: 30 mins, 242: 60 minutes, 243: 90 minutes, 244: 120 minutes
hdparm_spindown: 241  # doesnt work for 60 mins or longer.

### NUT #############################
nut_shutdown_threshold: 40 # 80 for testing, 40 for normal. percent.
ups_battery_charge_low: 75 # 75 for tests, 30 for normal. percent.
ups_battery_runtime_low: 2100 # 600 (10 mins) for normal, 2100 (35 mins) for testing

nut_ups_name: "ups"
nut_mode: "standalone"
nut_driver: "usbhid-ups"
nut_port: "auto"
nut_vendorid: "0764"
nut_productid: "0501"
nut_desc: "Home Server UPS (CyberPower CP900EPFCLCD)"
nut_pollinterval: 5
nut_maxretry: 3

nut_admin_user: "admin"
nut_admin_pass: "{{ vault_nut_admin_pass }}"
nut_mon_user: "monuser"
nut_mon_pass: "{{ vault_nut_mon_pass }}"

