TZ: Europe/Amsterdam

docker_compose_dir: "/srv/apps"
puid: 1001
guid: 1001
pgid: 1001

app_name: "openclaw"
openclaw_repo_url: "https://github.com/openclaw/openclaw.git"
openclaw_build_dir: "/srv/apps/openclaw-build"
openclaw_image_name: "openclaw:local"
