# media_vm/tasks/validate_paths.yml

---

- name: Validate base download directory exists
  stat:
    path: "{{ download_dir }}"
  register: download_dir_stat

- name: Fail if download dir does not exist
  fail:
    msg: "DOWNLOAD_DIR '{{ download_dir }}' does not exist on host!"
  when: not download_dir_stat.stat.exists

- name: Validate media directory exists
  stat:
    path: "{{ media_dir }}"
  register: media_dir_stat

- name: Fail if media dir does not exist
  fail:
    msg: "MEDIA_DIR '{{ media_dir }}' does not exist on host!"
  when: not media_dir_stat.stat.exists

- name: Check for bad volume path like downloads/downloads
  assert:
    that:
      - "'downloads/downloads' not in docker_volume_string"
    fail_msg: "You likely have a broken volume mount: 'downloads/downloads' — check .env.j2 and docker-compose.yaml!"
