# roles/media_vm/tasks/mount-smb.yml

---

- name: Create mount points for SMB shares
  file:
    path: "/mnt/media/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ smb_shares }}"

- name: Create SMB credentials file
  copy:
    dest: /etc/smb-media-credentials
    content: |
      username={{ smb_media_vm_username }}
      password={{ vault_smb_media_vm_password }}
    owner: root
    group: root
    mode: "0600"

- name: Register SMB share in fstab
  mount:
    path: "/mnt/media/{{ item.name }}"
    src: "//{{ smb_server }}/{{ item.name }}"
    fstype: cifs
    opts: "{{ smb_opts }}"
    state: mounted
  loop: "{{ smb_shares }}"
  register: fstab_entries

- name: Reload systemd units if fstab changed
  systemd:
    daemon_r3jeload: true
  when: fstab_entries is changed
