# roles/media_vm/tasks/mount-smb.yml

---

- name: Create mount points for SMB shares
  file:
    path: "/mnt/media/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ smb_shares }}"

- name: Create SMB credentials file
  copy:
    dest: /etc/smb-media-credentials
    content: |
      username={{ smb_media_vm_username }}
      password={{ vault_smb_media_vm_password }}
    owner: root
    group: root
    mode: '0600'

- name: Ensure /etc/fstab entries for SMB shares
  lineinfile:
    path: /etc/fstab
    line: "//{{ smb_server }}/{{ item.name }} /mnt/media/{{ item.name }} cifs credentials=/etc/smb-media-credentials,vers=3.0,uid=3002,gid=3002,file_mode=0664,dir_mode=0775 0 0"
    create: yes
    state: present
  loop: "{{ smb_shares }}"

  # src corresponds to a name in the trueNAS SMB shares menu.
- name: Mount all SMB shares
  mount:
    path: "/mnt/media/{{ item.name }}"
    src: "//{{ smb_server }}/{{ item.name }}"
    fstype: cifs
    opts: credentials=/etc/smb-media-credentials,vers=3.0,uid=3002,gid=3002,file_mode=0664,dir_mode=0775
    state: mounted
  loop: "{{ smb_shares }}"
