# roles/media_vm/tasks/provision.yml
---

- name: Set proxmox API facts explicitly
  set_fact:
    proxmox_api_host: "{{ hostvars['media-vm']['ansible_host'] }}"
    proxmox_node: "{{ proxmox_node_name }}"


- name: Check if VM exists
  community.general.proxmox_vm_info:
    api_user: root@pam
    api_password: "{{ vault_proxmox_password }}"
    api_host: "{{ hostvars['pve']['ansible_host'] }}"
    node: "{{ proxmox_node_name }}"
  register: vm_info
  delegate_to: pve

- name: Create VM shell if it does not exist
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ vault_proxmox_password }}"
    api_host: "{{ hostvars['pve']['ansible_host'] }}"
    node: "{{ proxmox_node_name }}"
    vmid: "{{ cloud_image_vmid }}"
    name: "{{ vm_config.name }}"
    memory: "{{ vm_config.memory }}"
    cores: "{{ vm_config.cores }}"
    ostype: l26
    scsihw: virtio-scsi-pci
    onboot: true
    state: present
    boot: order=scsi0
    ide:
      ide2: local:cloudinit
    ipconfig:
      ipconfig0: "{{ vm_config.ipconfig0 }}"
    net:
      net0: "virtio={{ vm_config.mac }},bridge={{ vm_config.net_bridge }}"
  when: "vm_config.name not in (vm_info.proxmox_vms | map(attribute='name') | list)"
  delegate_to: pve

- name: Import raw disk into Proxmox VM
  community.general.proxmox_disk:
    api_user: root@pam
    api_password: "{{ vault_proxmox_password }}"
    api_host: "{{ hostvars['pve']['ansible_host'] }}"
    vmid: "{{ cloud_image_vmid }}"
    disk: scsi0
    import_from: "/var/lib/vz/template/qemu/{{ cloud_image_filename }}"
    storage: "{{ cloud_image_storage }}"
    format: raw
    state: present
  delegate_to: pve
  become: true

- name: Resize imported disk
  ansible.builtin.command: >
    qm resize {{ cloud_image_vmid }} scsi0 {{ vm_config.disk_size }}
  delegate_to: pve
  become: true

- name: Finalize and start VM
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ vault_proxmox_password }}"
    api_host: "{{ hostvars['pve']['ansible_host'] }}"
    node: "{{ proxmox_node_name }}"
    vmid: "{{ cloud_image_vmid }}"
    name: "{{ vm_config.name }}"
    memory: "{{ vm_config.memory }}"
    cores: "{{ vm_config.cores }}"
    ostype: l26
    scsihw: virtio-scsi-pci
    onboot: true
    state: started

    boot: order=scsi0
    bootdisk: scsi0
    scsi:
      scsi0: "{{ cloud_image_storage }}:vm-{{ cloud_image_vmid }}-disk-0,format=raw"

    ide:
      ide2: local:cloudinit
    citype: nocloud
    ciuser: "{{ vm_config.ciuser }}"
    cipassword: "{{ vault_ubuntu_media_password }}"
    sshkeys: "{{ lookup('file', vm_defaults.ssh_key) }}"
    ipconfig:
      ipconfig0: "{{ vm_config.ipconfig0 }}"
    net:
      net0: "virtio={{ vm_config.mac }},bridge={{ vm_config.net_bridge }}"
    serial:
      serial0: socket
    force: true
  delegate_to: pve
