---
- name: Disable Proxmox enterprise repo
  lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb'
    line: '# deb http://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    state: present
  when: ansible_distribution == "Debian" and ansible_virtualization_type == "lxc"

- name: Add Proxmox no-subscription repo
  copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    owner: root
    group: root
    mode: '0644'
