# a hander is a deferred action. it runs once at the end of a play only if a task has 
# triggered it using `notify`. if it is triggered multiple times it still only runs once. 
# often used for restarting a service, or rebooting a machine.

---

- name: Restart media stack
  community.docker.docker_compose_v2:
    project_src: "{{ media_stack_base_dir }}"
    state: present
    recreate: auto
  become: false

- name: Restart qbittorrent
  ansible.builtin.shell: docker compose restart qbittorrent
  args:
    chdir: /srv/media
  listen: Restart qbittorrent
