# a hander is a deferred action. it runs once at the end of a play only if a task has 
# triggered it using `notify`. if it is triggered multiple times it still only runs once. 
# often used for restarting a service, or rebooting a machine.

---
- name: Restart media stack
  command: docker-compose down && docker-compose up -d
  args:
    chdir: "{{ media_stack_base_dir }}"
