# infra_vm/handlers/main.yml

---

- name: Restart ipmi_exporter
  systemd:
    name: ipmi_exporter
    state: restarted

- name: update docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: restart grafana
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - grafana
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: restart loki
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - loki
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: restart alloy
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - alloy
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: restart homepage
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - homepage
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: restart mkdocs
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - mkdocs
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: restart filebrowser
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - filebrowser
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false
