# infra_vm/handlers/main.yml

---

- name: Apply updated Docker Compose stack
  command: docker compose up -d
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart loki container
  command: docker compose restart loki
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart promtail container
  command: docker compose restart promtail
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart Grafana container
  command: docker compose restart grafana
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart Prometheus container
  command: docker compose restart prometheus
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart ipmi_exporter
  systemd:
    name: ipmi_exporter
    state: restarted

- name: Restart homepage container
  command: docker compose restart homepage 
  args:
    chdir: "{{ docker_compose_dir }}"

- name: Restart filebrowser container
  command: docker compose restart filebrowser
  args:
    chdir: "{{ docker_compose_dir }}"
