# roles/upload_cloud_image/tasks/main.yml
---

# Helps set up an Ubuntu VM by downloading the cloud image and uploading it to Proxmox

- name: Ensure cloud-images directory exists
  file:
    path: "{{ cloud_image_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Download Ubuntu cloud image if not already present
  get_url:
    url: "{{ cloud_image_url }}"
    dest: "{{ cloud_image_dir }}/{{ cloud_image_base_filename }}"
    mode: '0644'
  delegate_to: localhost

- name: Convert .img to .raw using qemu-img
  command: >
    qemu-img convert -O raw {{ cloud_image_dir }}/{{ cloud_image_base_filename }} {{ cloud_image_dir }}/{{ cloud_image_filename }}
  args:
    creates: "{{ cloud_image_dir }}/{{ cloud_image_filename }}"
  delegate_to: localhost

- name: Ensure Proxmox image upload directory exists
  file:
    path: "/var/lib/vz/template/qemu"
    state: directory
    mode: '0755'
  delegate_to: pve
  become: true

- name: Check if .raw file is already on Proxmox
  stat:
    path: "/var/lib/vz/template/qemu/{{ cloud_image_filename }}"
  register: proxmox_image_file
  delegate_to: pve
  become: true

- name: Upload .raw disk to Proxmox
  copy:
    src: "{{ cloud_image_dir }}/{{ cloud_image_filename }}"
    dest: "/var/lib/vz/template/qemu/{{ cloud_image_filename }}"
    mode: '0644'
    force: no
  when: not proxmox_image_file.stat.exists
  delegate_to: pve
  become: true

