{
 "title": "Proxmox",
 "description": "The server ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": "192.168.2.214:9221" }
  ]
 },
 "panels": [
  {
   "title": "Disk Power State (Standby vs Active)",
   "type": "timeseries",
   "description": "Shows the real-time and historical power state of each disk.\nStandby = 0, Active/Idle = 1, Unknown = -1, Error = -2.\nUseful for verifying spin-down behavior, monitoring disk usage patterns, and optimizing power consumption in NAS systems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(disk_power_state_value{type=\"hdd\", device!=\"/dev/sdd\"}, \"shortdev\", \"$1\", \"device\", \"/dev/(.+)\")",
     "legendFormat": "{{shortdev}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Container Memory Usage > 150MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"} / 1024 / 1024\n> 150",
     "legendFormat": "{{instance}}: {{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage (% per container across all nodes)",
   "type": "timeseries",
   "description": "Real-time CPU usage of each running Docker container across all monitored nodes: `media_vm`, `infra_vm`, and the Proxmox host.\n\nThis helps identify CPU-intensive containers (e.g. ffmpeg or qbittorrent) and track resource consumption trends across the system.\n\nCPU usage is measured as a percentage of a single core (100% = 1 core fully used).\n\nThe container names are derived from Docker Compose service labels (e.g. qbittorrent, grafana) and grouped by host.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (instance, container_label_com_docker_compose_service) (\n  rate(container_cpu_usage_seconds_total{name!=\"\"}[1m]) * 100\n) / scalar(\n  count(node_cpu_seconds_total{instance=\"proxmox\", mode=\"idle\"})\n))",
     "legendFormat": "{{container_label_com_docker_compose_service}} ({{instance}})"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Shows the amount of physical RAM currently in use on the Proxmox host, calculated as total memory minus available memory. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"proxmox\"} - node_memory_MemAvailable_bytes{instance=\"proxmox\"}) / 1024 / 1024 / 1024",
     "legendFormat": "Used RAM"
    },
    { "expr": "37.02", "legendFormat": "Max" }
   ]
  },
  {
   "title": "CPU Usage per VM/LXC",
   "type": "timeseries",
   "description": "The percentage of CPU capacity used by each virtual machine (QEMU) and container (LXC) on the Proxmox node. \n\nIt uses the `pve_cpu_usage_ratio` metric from the prometheus-pve-exporter, joined with guest metadata to label each line by guest name. \n\nCPU usage is shown relative to each guest’s allocated CPU quota. \n\nThis helps identify resource-intensive guests and spot spikes or background activity across the virtualized environment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio * on(id) group_left(name) pve_guest_info * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "description": "Component temperatures collected via IPMI and smartctl, including CPU, memory, HDDs and chipset elements.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(ipmi_temperature_celsius{name!~\"CPU0_DTS|VR_TEMP|B550_FCH_TEMP|VR_TEMP\"}[1m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "smartctl_device_temperature{temperature_type=\"current\",device!~\"sdd|sdb\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "Displays total CPU usage for the Proxmox node, calculated as 100% minus average idle time across all CPU cores.\nData is scraped via node_exporter and shown as a 1-minute rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"proxmox\"}[1m])) * 100)",
     "legendFormat": "Total CPU"
    },
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{mode=\"iowait\", instance=\"proxmox\"}[1m])) * 100",
     "legendFormat": "IO Wait"
    },
    { "expr": "radeontop_gpu_percent   ", "legendFormat": "iGPU %" },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"proxmox\"}[10m])) * 100)",
     "legendFormat": "10m Avg"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "description": "Displays real-time RPM values for critical system fans reported via IPMI, including the CPU fan (CPU0_FAN) and system fans (SYS_FAN1, SYS_FAN3). This chart helps monitor cooling performance and detect potential fan failures or irregularities. Values are collected using ipmi_exporter at 15-second intervals.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "ipmi_fan_speed_rpm  ", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Tech Shelf Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.tech_shelf_power\"}",
     "legendFormat": "Power"
    },
    {
     "expr": "avg_over_time(homeassistant_sensor_power_w{entity=\"sensor.tech_shelf_power\"}[60m])",
     "legendFormat": "1hr average"
    },
    {
     "expr": "avg_over_time(homeassistant_sensor_power_w{entity=\"sensor.tech_shelf_power\"}[3d])",
     "legendFormat": "3day average"
    }
   ]
  },
  {
   "title": "RAM Usage per VM/LXC",
   "type": "timeseries",
   "description": "Memory usage per guest in percent. It calculates the ratio of pve_memory_usage_bytes to pve_memory_size_bytes. \n\nIdentify memory-heavy workloads and monitor for over- or under-provisioned guests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes / pve_memory_size_bytes) * on(id) group_left(name) pve_guest_info * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"proxmox\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"proxmox\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"proxmox\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"proxmox\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"proxmox\",template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"proxmox\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=\"proxmox\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info{type=\"lxc\"})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=\"proxmox\"}[5m]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} RECEIVE"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=\"proxmox\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} SEND"
    }
   ]
  }
 ]
}