# Global defaults
nfs_client_packages:
  - nfs-common
  - acl

truenas_ip: "192.168.2.104"

nfs_user_name: nfs_user
nfs_user_uid: 1001
nfs_user_gid: 1001

nfs_opts_items:
  - _netdev
  - hard
  - nofail
  - proto=tcp
  - retrans=2
  - timeo=150
  - vers=4.2
  - x-systemd.automount
  - x-systemd.idle-timeout=60s

nfs_opts_default: "{{ nfs_opts_items | join(',') }}"
