# Global defaults
nfs_client_packages:
  - nfs-common
  - acl

# Per-host list of NFS mounts
# Each item can override opts; opts_default used when omitted
nfs_client_opts_default: "vers=4.2,proto=tcp,hard,timeo=600,retrans=2,_netdev,nofail"


truenas_ip: "192.168.2.104"
nfs_opts: "vers=4.2,proto=tcp,soft,timeo=5,retrans=2,_netdev,nofail"


# Dont run like this - itll create every mount on every host
# nfs_client_mounts:
#   - name: library
#     target: "/mnt/tank/library"
#     mountpoint: "/mnt/nfs/library"
#   - name: media
#     target: "/mnt/tank/media"
#     mountpoint: "/mnt/nfs/media"
#   - name: youtube-kids
#     target: "/mnt/tank/youtube-kids"
#     mountpoint: "/mnt/nfs/youtube-kids"
#   - name: immich
#     target: "/mnt/tank/immich"
#     mountpoint: "/mnt/nfs/immich"
#   - name: paperless
#     target: "/mnt/tank/paperless"
#     mountpoint: "/mnt/nfs/paperless"
