- name: Systemd daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart autofs
  become: true
  listen: Restart autofs
  ansible.builtin.systemd:
    name: autofs
    state: restarted
