---

- name: Restart Docker Compose stack
  ansible.builtin.command: docker compose -f /srv/apps/docker-compose.yml up -d
  args:
    chdir: /srv/apps

- name: Restart Alloy 
  ansible.builtin.command: docker compose -f /srv/apps/docker-compose.yml restart alloy
  args:
    chdir: /srv/apps
