# share_drive_probe/handlers/main.yml

---

# handlers run in the order they are definied in handlers/main.yml

- name: reload daemon
  systemd:
    daemon_reload: true

- name: restart share-drive-probe timer
  systemd:
    name: share-drive-probe.timer
    state: restarted
    enabled: true

- name: run share-drive-probe service
  systemd:
    name: share-drive-probe.service
    state: restarted
    enabled: true
