# share_drive_probe/handlers/main.yml

---

# handlers run in the order they are definied

- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart share-drive-probe timer
  ansible.builtin.systemd:
    name: share-drive-probe.timer
    state: restarted
    enabled: true

- name: Run share-drive-probe service
  ansible.builtin.systemd:
    name: share-drive-probe.service
    state: restarted
    enabled: false
