# share_drive_probe/handlers/main.yml

---

- name: Daemon reload
  systemd:
    daemon_reload: true

- name: Restart share-drive-probe timer
  systemd:
    name: share-drive-probe.timer
    state: restarted
    enabled: true
