# roles/zram/tasks/main.yml
---
- name: Install zram-tools
  apt:
    name: zram-tools
    state: present

- name: Configure ZRAM
  copy:
    dest: /etc/default/zramswap
    content: |
      ALGO=lz4
      PERCENT=50
      PRIORITY=100
      ZRAM_DEVICES=1

- name: Enable zramswap
  systemd:
    name: zramswap
    enabled: yes
    state: restarted
