# infra_vm/files/homepage_config/bookmarks.yaml

# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Media Apps:
    - Jellyfin:
        - abbr:
          href: http://192.168.2.110:8096
    - Immich:
        - abbr:
          href: http://192.168.2.113:2283
    - Paperless:
        - abbr:
          href: http://192.168.2.117:8000
    - Tubearchivist:
        - abbr:
          href: http://192.168.2.116:8000
    - BookLore:
        - abbr:
          href: http://192.168.2.105:6060
    - Jellyseer:
        - abbr:
          href: http://192.168.2.105:5055
    - Sonarr:
        - abbr:
          href: http://192.168.2.105:8989
    - Radarr:
        - abbr:
          href: http://192.168.2.105:7878
    - Sabnzbd:
        - abbr:
          href: http://192.168.2.105:8081
    - qBittorrent:
        - abbr:
          href: http://192.168.2.105:8080
    - Gluetun:
        - abbr:
          href: http://192.168.2.105:8000/v1/publicip/ip

- Observability:
    - Grafana:
        - abbr:
          href: http://192.168.2.106:3000
    - Loki:
        - abbr:
          href: http://192.168.2.106:3100/config
    - Prometheus:
        - abbr:
          href: http://192.168.2.115:9090
    - Container Status Exporter Endpoint:
        - abbr:
          href: http://192.168.2.106:8081/metrics
    - Uptime Kuma:
        - abbr:
          href: http://192.168.2.106:3001
    - TrueNas Alloy:
        - abbr:
          href: http://192.168.2.104:12345
    - Infra Alloy:
        - abbr:
          href: http://192.168.2.106:12345
    - Media Alloy:
        - abbr:
          href: http://192.168.2.105:12345
    - Tubearchivist Alloy:
        - abbr:
          href: http://192.168.2.116:12345
    - Prometheus Alloy:
        - abbr:
          href: http://192.168.2.115:12345
    - Immich Alloy:
        - abbr:
          href: http://192.168.2.113:12345
    - Open-UI Alloy:
        - abbr:
          href: http://192.168.2.119:12345
    - Jellyfin Alloy:
        - abbr:
          href: http://192.168.2.110:12345
    - Paperless Alloy:
        - abbr:
          href: http://192.168.2.117:12345
    - Traefik Alloy:
        - abbr:
          href: http://192.168.2.108:12345

- Other Apps:
    - TrueNAS:
        - abbr:
          href: http://192.168.2.104
    - Homepage:
        - abbr:
          href: http://192.168.2.106:3002
    - Traefik:
        - abbr:
          href: http://192.168.2.108/dashboard/
    - Home Assistant:
        - abbr:
          href: http://192.168.2.102:8123
    - AdGuard:
        - abbr:
          href: http://192.168.2.111
    - Docs:
        - abbr:
          href: http://192.168.2.106:8000

- Hardware_:
    - Proxmox:
        - abbr:
          href: http://192.168.2.214:8006
    - PBS:
        - abbr:
          href: http://192.168.2.200:8007
    - BMC:
        - abbr:
          href: http://192.168.2.213
    - Router:
        - abbr:
          href: http://192.168.2.254
    - MikroTik Router:
        - abbr:
          href: http://192.168.88.1/

- Docs:
    - Server:
        - abbr:
          href: https://docs.itsa.pizza
    - Proxmox Scripts:
        - abbr:
          href: https://community-scripts.github.io/ProxmoxVE/scripts
