# infra_vm/files/homepage_config/bookmarks.yaml

---

# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Media Apps:
    - Jellyfin:
        - abbr: 
          href: http://192.168.2.110:8096
    - Jellyseer:
        - abbr: 
          href: http://192.168.2.105:5055
    - Paperless:
        - abbr:
          href: http://192.168.2.117:8000
    - Tubearchivist:
        - abbr:
          href: http://192.168.2.116:8000
    - Hometube:
        - abbr: 
          href: http://192.168.2.105:8501/
    - Sonarr:
        - abbr: 
          href: http://192.168.2.105:8989
    - Radarr:
        - abbr: 
          href: http://192.168.2.105:7878
    - Sabnzbd:
        - abbr: 
          href: http://192.168.2.105:8081
    - qBittorrent:
        - abbr: 
          href: http://192.168.2.105:8080
    - Gluetun:
        - abbr: 
          href: http://192.168.2.105:8000/v1/publicip/ip
    - BookLore:
        - abbr:
          href: http://192.168.2.105:6060
    - Immich:
        - abbr:
          href: http://192.168.2.113:2283
    - Tunarr:
        - abbr:
          href: http://192.168.2.110:8000

- Infra Apps:
    - TrueNAS:
        - abbr: 
          href: http://192.168.2.104
    - Grafana:
        - abbr: 
          href: http://192.168.2.106:3000
    - Prometheus:
        - abbr: 
          href: http://192.168.2.115:9090
    - Uptime Kuma:
        - abbr:
          href: http://192.168.2.106:3001

- Services:
    - Home Assistant:
        - abbr: 
          href: http://192.168.2.102:8123
    - AdGuard:
        - abbr: 
          href: http://192.168.2.111
    - VaultWarden:
        - abbr:
          href: https://192.168.2.13:8000

- Hardware_:
    - ProxMox:
        - abbr: 
          href: http://192.168.2.214:8006
    - PBS:
        - abbr:
          href: http://192.168.2.200:8007
    - BMC:
        - abbr:
          href: http://192.168.2.213
    - Router:
        - abbr:
          href: http://192.168.2.254

- Docs:
  - Proxmox Scripts:
    - abbr: 
      href: https://community-scripts.github.io/ProxmoxVE/scripts
