# infra_vm/files/homepage_config/bookmarks.yaml

---

# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Apps:
    - Grafana:
        - abbr: I
          href: http://192.168.2.106:3000
    - Loki:
        - abbr: I
          href: http://192.168.2.106:3100
    - Kavita:
        - abbr: M
          href: http://192.168.2.105:5000
    - TrueNAS:
        - abbr: NAS 
          href: http://192.168.2.104:5000

- _Hardware:
    - ProxMox:
        - abbr: Pm 
          href: http://192.168.2.214:8006
    - PBS:
        - abbr: PBS 
          href: http://192.168.2.200:8007
    - BMC:
        - abbr: BMC 
          href: http://192.168.2.213
    - Router:
        - abbr:
          href: http://192.168.2.254

- Docs:
  - Loki:
    - abbr: Lo
      href: https://grafana.com/docs/loki/latest/reference/loki-http-api/
  - Scripts:
    - abbr: 
      href: https://community-scripts.github.io/ProxmoxVE/scripts
