# infra_vm/files/homepage_config/settings.yaml

---

# For configuration options and examples, please see:
# # https://gethomepage.dev/configs/settings/

title: Home Server
description: Media and Infra Apps

theme: light # or dark
fullWidth: false
# maxGroupColumns: 8 # default is 4 for services, 6 for bookmarks, max 8

useEqualHeights: false 

layout:

  Infra-1:
    tab: Infra
    style: row
    columns: 4

  Infra-2:
    tab: Infra
    initiallyCollapsed: false
    style: row
    columns: 4

  PVE:
    tab: Infra
    initiallyCollapsed: false
    style: row
    columns: 3

  Hardware:
    tab: Infra
    initiallyCollapsed: false
    style: row
    columns: 3


  Media-1:
    tab: Media
    style: row
    columns: 3
  Media-2:
    tab: Media
    initiallyCollapsed: false
    style: row
    columns: 2
  Usenet:
    tab: Media
    initiallyCollapsed: false
    style: row
    columns: 4


  Metrics:
    tab: Metrics
    style: row
    columns: 3

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
