# infra_vm/files/homepage_config/settings.yaml

---

# For configuration options and examples, please see:
# # https://gethomepage.dev/configs/settings/

title: Home Server
description: Media and Infra Apps

theme: light # or dark
fullWidth: false
# maxGroupColumns: 8 # default is 4 for services, 6 for bookmarks, max 8

useEqualHeights: false 

layout:
  Media-1:
    style: row
    columns: 3
  Media-2:
    initiallyCollapsed: true
    style: row
    columns: 2

  Infra-1:
    style: row
    columns: 4

  Infra-2:
    initiallyCollapsed: false
    style: row
    columns: 4

  PVE:
    initiallyCollapsed: false
    style: row
    columns: 3

  Hardware:
    initiallyCollapsed: false
    style: row
    columns: 3

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
