# infra_vm/files/homepage_config/widgets.yaml

---

# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- datetime:
    text_size: xl
    format:
      timeStyle: short

- glances:
    url: http://192.168.2.214:61208
    version: 4
    cpu: true 
    memory: true
    uptime: true 

