# infra_vm/files/homepage_config/widgets.yaml

---

# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
