# smb_shares:
#   - name: immich 
#     target: /mnt/immich

nfs_shares:
  - name: immich
    mountpoint: /mnt/nfs/immich
    target: /mnt/tank/immich
  - name: movies
    mountpoint: /mnt/nfs/movies
    target: /mnt/tank/movies
  - name: photos
    mountpoint: /mnt/nfs/photos
    target: /mnt/tank/photos
