# Shell environment configuration
# Explicitly define users since auto-discovery only finds UID >= 1000
# Format: username:home_dir:shell
shell_environment_shell_users:
  - "root:/root:/bin/bash"

nfs_shares:
  # - name: immich
  #   mountpoint: /mnt/nfs/immich
  #   target: /mnt/tank/immich
  - name: photos
    mountpoint: /mnt/nfs/photos
    target: /mnt/tank/photos
