nfs_shares:
  - name: library
    mountpoint: /mnt/nfs/library
    target: /mnt/tank/library
  - name: media
    mountpoint: /mnt/nfs/media
    target: /mnt/tank/media
  - name: youtube-kids
    mountpoint: /mnt/nfs/youtube-kids
    target: /mnt/tank/youtube-kids

smb_shares:
  - name: library 
    target: /mnt/media/library
    mountpoint: /mnt/media/library
  - name: media 
    target: /mnt/media/media
    mountpoint: /mnt/media/media
  - name: youtube-kids 
    target: /mnt/youtube-kids
    mountpoint: /mnt/media/youtube-kids

