# host_vars/media-vm.yml
ansible_host: 192.168.2.216
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

proxmox_node_name: proxmox

mediaVM:
  ip: 192.168.2.216
  ipconfig0: "ip=192.168.2.216/24,gw=192.168.2.254"
  mac: "02:00:00:12:34:56"
  ciuser: "ubuntu"
  net_bridge: "vmbr0"
