nfs_shares:
  - name: library
    mountpoint: /mnt/nfs/library
    target: /mnt/tank/library
  - name: media
    mountpoint: /mnt/nfs/media
    target: /mnt/tank/media
  - name: books
    mountpoint: /mnt/nfs/books
    target: /mnt/tank/books
