# proxmox_node/handlers/main.yml

---

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart ipmi_exporter
  systemd:
    name: ipmi_exporter
    state: restarted
    enabled: yes

- name: Restart pve_exporter
  systemd:
    name: pve_exporter
    state: restarted
    enabled: yes

- name: Restart Glances
  systemd:
    name: glances
    state: restarted

- name: Restart nut-server
  ansible.builtin.systemd:
    name: nut-server
    state: restarted
    enabled: true

- name: Restart nut-monitor
  ansible.builtin.systemd:
    name: nut-monitor
    state: restarted
    enabled: true

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart ups-battery-monitor.timer
  ansible.builtin.systemd:
    name: ups-battery-monitor.timer
    state: restarted
    enabled: true
