- name: Restart sleep-hours timers
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - docker-sleep@pause.timer
    - docker-sleep@unpause.timer
