# playbooks/document_library_lxc.yml

- name: Document Library LXC
  hosts: document_library_lxc
  gather_facts: true
  become: true

  roles:
    - role: nfs_client
      tags: nfs
    - role: share_drive_probe
      tags: shares
    - role: document_library_lxc
      tags: document_library
    - role: sleep_hours
      tags: sleep
    - role: shell_environment
      tags: shell
    - role: tailscale
      tags: tailscale
