# playbooks/immich_lxc.yml

---

- name: Immich LXC
  hosts: immich_lxc
  gather_facts: true
  become: true

  roles:
    - role: nfs_client
      tags: [nfs]
    - role: immich_lxc
      tags: [immich]
    - role: share_drive_probe 
      tags: [shares]

  vars:
    foo: bar
    # NFS
    nfs_client_mounts:
      - name: immich
        mountpoint: /mnt/nfs/immich
        target: /mnt/tank/immich
