# playbooks/key_server.yml


- name: Key Server
  hosts: key_server
  gather_facts: true
  become: true

  roles:
    - role: key_server
      tags: key_server
    - role: shell_environment
      tags: shell

  vars:
    ciuser: "{{ vm_defaults.ciuser }}"
    ssh_key: "{{ vm_defaults.ssh_key }}"

    ansible_api_user: root@pam
    ansible_ssh_private_key_file: ~/.ssh/john_macbook
