# playbooks/media_vm.yml

---

- name: Media VM
  hosts: media-vm
  gather_facts: true
  become: true

  roles:
    - role: media_vm
      tags: media_vm

  vars:
    proxmox_node_name: proxmox
    ciuser: "{{ vm_defaults.ciuser }}"
    ssh_key: "{{ vm_defaults.ssh_key }}"

    ansible_api_user: root@pam
    ansible_ssh_private_key_file: ~/.ssh/john_macbook

    vm_name: media
    vm_id: 105 
    vm_cloud_init_user: john 
    vm_cloud_init_mac: 02:00:00:00:01:05 
    vm_ip_address: 192.168.2.105
