# playbooks/media_vm.yml

---

- name: Media VM
  hosts: media
  gather_facts: false
  become: true

  roles:
    - role: media_vm
      tags: media_vm

  vars:
    ansible_host: 192.168.2.214
    ansible_user: root
    ansible_api_user: root@pam
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    email_address: "mthwsjc@gmail.com"
    proxmox_node_name: proxmox
    vm_name: media
    ciuser: "{{ vm_defaults.ciuser }}"
    ssh_key: "{{ vm_defaults.ssh_key }}"
