# playbooks/n8n_lxc.yml

- name: N8n LXC
  hosts: n8n_lxc
  gather_facts: true
  become: true

  roles:
    # - role: nfs_client
    #   tags: nfs
    #   when: nfs_shares is defined and nfs_shares | length > 0
    # - role: share_drive_probe
    #   tags: shares
    #   when: nfs_shares is defined and nfs_shares | length > 0
    - role: n8n_lxc
      tags: n8n
    - role: shell_environment
      tags: shell
    - role: tailscale
      tags: tailscale

  # - role: sleep_hours
  #   tags: sleep
  #   when: sleep_hours_enabled | default(false) | bool
