- name: TrueNAS VM
  hosts: nas
  gather_facts: true
  become: true

  vars:
    email_address: "mthwsjc@gmail.com"
    proxmox_node_name: pve
    vm_name: truenas
    mac_address: "02:00:00:00:00:04"
    cores: 4
    memory: 12288
    disk_size: 128
    disk_storage: local-zfs
    iso_storage: local
    iso_filename: TrueNAS-SCALE-24.10.2.1.iso

  roles:
    - role: nas
      tags: truenas,nas
