# playbooks/immich_lxc.yml

---

- name: Paperless LXC
  hosts: paperless_lxc
  gather_facts: true
  become: true

  roles:
    - role: nfs_client
      tags: [nfs]
    - role: paperless_lxc
      tags: [paperless]

  vars:
    # NFS
    nfs_client_mounts:
      - name: paperless
        mountpoint: /mnt/nfs/paperless
        target: /mnt/tank/paperless
