# playbooks/paperless_lxc.yml

---

- name: Paperless LXC
  hosts: paperless_lxc
  gather_facts: true
  become: true

  roles:
    - role: nfs_client
      tags: [nfs]
    - role: share_drive_probe 
      tags: [shares]
    - role: paperless_lxc
      tags: [paperless]
