# playbooks/immich_lxc.yml

- name: Prometheus LXC
  hosts: prometheus_lxc
  gather_facts: true
  become: true

  roles:
    - role: prometheus_lxc
      tags: prometheus
    - role: shell_environment
      tags: shell
    - role: tailscale
      tags: tailscale
