# playbooks/proxmox_node.yml

---

- name: Proxmox node
  hosts: proxmox
  become: true
  roles:
    - role: nfs_client
      tags: nfs
    - role: share_drive_probe 
      tags: shares
    - role: pve 
      tags: pve
