# playbooks/proxmox_node.yml

- name: Proxmox node
  hosts: proxmox
  become: true
  roles:
    - role: pve
      tags: pve
    - role: proxmox_lxc_tun
      tags: tailscale
    - role: shell_environment
      tags: shell
    - role: tailscale
      tags: tailscale
