# playbooks/traefik_lxc.yml


- name: Traefik LXC
  hosts: traefik_lxc
  gather_facts: true
  become: true

  roles:
    - role: traefik_lxc
      tags: traefik
    - role: shell_environment
      tags: shell

  vars:
    foo: bar
