# playbooks/immich_lxc.yml

- name: Tubearchivist LXC
  hosts: tubearchivist_lxc
  gather_facts: true
  become: true

  roles:
    - role: nfs_client
      tags: nfs
    - role: share_drive_probe
      tags: shares
    - role: tubearchivist_lxc
      tags: tubearchivist
    - role: sleep_hours
      tags: sleep
    - role: shell_environment
      tags: shell
