# playbooks/immich_lxc.yml

---

- name: Tubearchivist Kids LXC
  hosts: tubearchivist_kids_lxc
  gather_facts: true
  become: true

  roles:
    - role: tubearchivist_kids_lxc
      tags: tubearchivist, tubearchivist_kids
