# playbooks/immich_lxc.yml

---

- name: Tubearchivist LXC
  hosts: tubearchivist_lxc
  gather_facts: true
  become: true

  roles:
    - role: tubearchivist_lxc
      tags: [tubearchivist]
    - role: nfs_client
      tags: [nfs]
    - role: share_drive_probe 
      tags: [shares]

  vars:
    nfs_client_mounts:
      - name: youtube-kids
        mountpoint: /mnt/nfs/youtube-kids
        target: /mnt/tank/youtube-kids
