# traefik_lxc/handlers/main.yml

---

- name: Restart docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - traefik
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false

- name: Restart alloy
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    services:
      - alloy
    state: present
    recreate: always
    dependencies: true
    remove_orphans: true
  become: false
