- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: /srv/apps/navidrome/data, owner: "{{ puid }}", group: "{{ guid }}" }
    - { path: /srv/apps/alloy, owner: root, group: root }
  tags: alloy, docker
  notify:
    - restart alloy
- name: Upload alloy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ puid }}"
    group: "{{ guid }}"
    mode: '0644'
  loop:
    - alloy:
      src: templates/config.alloy
      dest: /srv/apps/alloy/config.alloy
  become: true
  tags: [docker, alloy]
  notify:
    - restart alloy
- name: Copy docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: /srv/apps/docker-compose.yml
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart docker compose stack
  tags: docker, alloy
