# traefik_lxc/tasks/main.yml
- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ docker_compose_dir }}/alloy"
    - "{{ docker_compose_dir }}/traefik/dynamic"
  tags: traefik
- name: Copy Alloy config
  copy:
    src: files/config.alloy
    dest: "{{ docker_compose_dir }}/alloy/config.alloy"
    owner: root
    group: docker
    mode: '0644'
  notify: restart alloy
  tags: alloy
- name: Template Traefik config
  template:
    src: traefik.yml.j2
    dest: "{{ docker_compose_dir }}/traefik/traefik.yml"
    owner: root
    group: docker
    mode: '0644'
  notify: restart traefik
  tags: traefik
- name: Template Traefik dynamic routers
  template:
    src: routers.yml.j2
    dest: "{{ docker_compose_dir }}/traefik/dynamic/routers.yml"
    owner: root
    group: docker
    mode: '0644'
  notify: restart traefik
  tags: traefik
- name: Copy docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart docker compose stack
  tags: docker
