# traefik_lxc/tasks/main.yml

---

- name: Create base app directories for containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ docker_compose_dir }}/alloy"
    - "{{ docker_compose_dir }}/traefik"


- name: Template Traefik config
  template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ docker_compose_dir }}/prometheus/prometheus.yml"
    owner: root
    group: docker
    mode: '0644'
  notify: restart prometheus


- name: Copy docker-compose.yml
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
  notify: 
    - restart docker compose stack
