# traefik_lxc/tasks/main.yml

---

- name: Ensure /etc/traefik exists
  file:
    path: /etc/traefik
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Upload traefik.yaml config
  copy:
    src: traefik_config.yaml
    dest: /etc/traefik/traefik.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Traefik

- name: Ensure /etc/traefik/conf.d/ exists
  file:
    path: /etc/traefik/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Upload providers.yml config
  template:
    src: files/providers.yml.j2
    dest: /etc/traefik/conf.d/providers.yaml
    owner: root
    group: root
    mode: '0644'
  notify: Restart Traefik
